### ISSUE TITLE
page breaks?  selected lists?

### ISSUE THREAD

**Issue by denfc** [dcapslock/TrelloPrinter#1]
First, thank you!  We're using Trello to track our results in meeting some strategic plan objectives, and we want to be able to print, which we can do thanks to your software.  But our board is big, and we would like to be able to print either selected parts, e.g., project leader by project leader, or at least separate the different lists (and maybe even cards) by having them start on different pages.

Do you have any notion to implement this sort of functionality, or anything close?  Thanks.

-- dfc

**Comment by dcapslock** [comment]
Hi, you should be able to select lists and cards to print by using the Check boxes next to each list and cards. If that does not suit please provide more details. 

How would you like pagination (page breaks) to be done? It may be tricky due to browser support of page breaks.

**Comment by denfc** [comment]
Feel stupid to admit that I never tried the check boxes, perhaps because
they were all checked!  That method may be somewhat tedious, but it should
get us to where we want.

I was thinking that pagination might work with the option for each list to
start on a new page.

Many thanks for your quick response.

-- dfc
