### ISSUE TITLE
Problem printing headings

### ISSUE THREAD

**Issue by brannonh** [dcapslock/TrelloPrinter#2]
I just discovered this, and I must say it's genius.

That being said, I'm having an issue printing. The headings for members and due date are being printed on new lines for some reason. Any idea what's causing it? It seems to happen, regardless of the card title length.

![capture](https://user-images.githubusercontent.com/15135353/32913754-e2bb7992-cad8-11e7-98c0-cf4638dfac1a.PNG)

![image](https://user-images.githubusercontent.com/15135353/32913824-23115386-cad9-11e7-9395-322f185c4570.png)

![image](https://user-images.githubusercontent.com/15135353/32913857-446a8c28-cad9-11e7-97f4-8652502a1c33.png)

**Comment by dcapslock** [comment]
Best results are achieved with Chrome using Save As PDF print option.

That being said I use landscape. From the screen shot I see that bootstrap is doing what it needs to do and stacking the columns. That is where changes would need to be made. However I time poor at the moment to change the template.

________________________________

**Comment by brannonh** [comment]
Thanks for the quick reply. I tried use the Save As PDF and landscape options, but it's still stacking the columns.

I've been playing around with it a bit, and I've had some success changing the column classes to col-xs-\*, rather than col-sm-\*. I may just update the template.

**Comment by brannonh** [comment]
I was able to fix this issue by editing the template, as mentioned in my previous comment.
